### ISSUE TITLE
Tests with netdumbster fail on github action

### ISSUE THREAD

**Issue by VILLAN3LL3** [cmendible/netDumbster#31]
If I run the tests locally, everything is fine.
But they are executed by a github action, they fail with the following error:

>  Error Message:
>    System.Net.Sockets.SocketException : Permission denied
>   Stack Trace:
>      at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
>    at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
>    at System.Net.Sockets.Socket.Bind(EndPoint localEP)
>    at System.Net.Sockets.TcpListener.Start(Int32 backlog)
>    at System.Net.Sockets.TcpListener.Start()
>    at netDumbster.smtp.SimpleSmtpServer.StartListening()
>    at netDumbster.smtp.SimpleSmtpServer.Start(Configuration configuration)
>    at netDumbster.smtp.Configuration.Build()

Any ideas?

**Comment by cmendible** [comment]
Hi can you give me more details? 

I use actions to run the tests without issues using .NET Core 3.1: https://github.com/cmendible/netDumbster/blob/edabbce7be4cf2cc02e2dce5efd2e6b733b5aa2b/.github/workflows/netDumbster.yml#L20

Also there is a known issue with .NET 5: https://github.com/cmendible/netDumbster/issues/30

**Comment by VILLAN3LL3** [comment]
Hi
thank you for the quick reply. Update: This error does only occur if using ubuntu-latest. If I use windows-latest everything is fine.

**Comment by cmendible** [comment]
I see. Perhaps is related to https://github.com/cmendible/netDumbster/issues/28 but haven't had the time to understand what is going on there...

Any help would be much appreciated.

**Comment by VILLAN3LL3** [comment]
Here's a hint of a colleague of mine: 

> Under POSIX operating systems you need root rights if a server is to be started on ports <1000

I'm using port 25 for my tests

**Comment by cmendible** [comment]
Thanks that fixed a issue I was having with some test on linux!

Did changing the port work for you?

**Comment by VILLAN3LL3** [comment]
I haven't tried it yet because it's fine with me at the moment if the build is running on a Windows machine

**Comment by cmendible** [comment]
I'm going to add a a check for this case in the code and log a warning before closing the issue.
